apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopper-api-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: shopper-api-service
              port:
                number: 9000
